title: kineticEQ
description: kineticEQ docs - High-Performance Kinetic Equation Solver

remote_theme: just-the-docs/just-the-docs@v0.7.0

plugins:
  - jekyll-remote-theme

search_enabled: true

color_scheme: light
color_scheme_toggle: true

aux_links:
  "GitHub": https://github.com/Minamium/kineticEQ
aux_links_new_tab: true
